#!/bin/bash

echo `date +"%y%m%d%H%M%S"` > CapCompileDate
CAPCOMPILEDATE=`cat CapCompileDate`
CAP_DIR=`pwd`
XENVLUMAX_DIR=$CAP_DIR/../..
FSGPP_DIR=$XENVLUMAX_DIR/src/fsgpp
CAPTURE_DIR=$XENVLUMAX_DIR/src/capture

cd $CAPTURE_DIR
CAPTURE_HASH=`git rev-parse HEAD`

cd $FSGPP_DIR
FSGPP_HASH=`git rev-parse HEAD`

cd $CAP_DIR
CAP_HASH=`git rev-parse HEAD`

echo capture_hash: $CAPTURE_HASH
echo fsgpp_hash: $FSGPP_HASH
echo cap_hash: $CAP_HASH

echo "/*Version.h      */" > Version.h
echo "/*do not edit this file */" >> Version.h
echo " " >> Version.h
echo "#ifndef __VERSION_H__" >> Version.h
echo "#define __VERSION_H__" >> Version.h
echo " " >> Version.h
echo "static const char * CAP_VERSION =\"${CAP_HASH}\";" >> Version.h
echo "static const char * FSGPP_VERSION =\"${FSGPP_HASH}\";" >> Version.h
echo "static const char * CAPTURE_VERSION =\"${CAPTURE_HASH}\";" >> Version.h
echo "static const char * CAPCOMPILEDATE =\"${CAPCOMPILEDATE}\";" >> Version.h
echo " " >> Version.h
echo " " >> Version.h
echo "#endif /* __VERSION_H__ */" >> Version.h
exit
